clear;
clc;
% close all;

n_method=7;
font_size=12;

addpath('results\');
load results_cod-rna_min_max_scaling_large.mat

results_size=results(:,1);

method_name=["SeDuMi" ...
    'MOSEK' ...
    'CDCS (8)' ...
    'BCR' ...
    'SDcut' ...
    'CDCS (20)' ...
    '\color{black}\bfGDPA'];

ncolors = distinguishable_colors(n_method);
figure();hold on;
for i=1:n_method % number of methods
    if i<=4
        plot(results(1:6,1),results(1:6,i+1),...
            'LineStyle','none',...
            'LineWidth',1,...
            'Marker','+',...
            'color',ncolors(i,:),'DisplayName',num2str(method_name(i)));
    elseif i>4 && i<=5 
        plot(results(1:6,1),results(1:6,i+1),...
            'LineStyle','none',...
            'LineWidth',1,...
            'Marker','s','color',ncolors(i,:),'DisplayName',num2str(method_name(i)));
    elseif i==6
        plot(results(1:6,1),results(1:6,i+1),...
            'LineStyle','none',...
            'LineWidth',1,...
            'Marker','p','color',ncolors(i,:),'DisplayName',num2str(method_name(i))); 
    elseif i==7
        plot(results(:,1),results(:,i+1),...
            'LineStyle','none',...
            'LineWidth',1,...
            'Marker','o','color','blue','DisplayName',num2str(method_name(i)));
    end
end

xlabel('problem size', 'FontSize', font_size);
ylabel('runtime (ms)', 'FontSize', font_size);
set(gca,'fontname','times', 'FontSize', font_size)  % Set it to times
xlim([min(results(:,1)) max(results(:,1))]);
results(:,1)=[];
results(results==0)=[];
ylim([min(vec(results)) max(vec(results))]);
grid on;
set(gca, 'xScale', 'log')
set(gca, 'YScale', 'log')
legend;
title('Fig.4 right');