function [ M_current_eigenvector0,...
    scaled_M,...
    scaled_factors,lmin ] = ...
    compute_scalars_scal( ...
    M_updated_current,...
    M_current_eigenvector0,...
    scalll)

[M_current_eigenvector0,lmin] = ...
    lobpcg_fv(...
    M_current_eigenvector0,...
    M_updated_current*1/1,...
    1e-4,...
    200);
%     1e-16,...
%     1e3

a=M_current_eigenvector0(:,1);

scaled_M = (1./a) .* M_updated_current .* a';
scaled_factors = (1./a) .* ones(length(M_current_eigenvector0)) .* a';

end

