function [y,z]=LP_solve_1offdia_2dia( ...
    n_sample,...
    scaled_M,...
    scaled_factors,...
    rho,...
    i,...
    db,...
    options,...
    counter,...
    y,...
    y_sign,...
    z)

[ s_k1 ] = ...
    LP_solve_1offdia_2dia_core( ...
    1,...
    options,...
    db,...
    rho,...
    scaled_M,...
    scaled_factors,...
    n_sample,...
    i,...
    y,...
    y_sign);

[ s_k2 ] = ...
    LP_solve_1offdia_2dia_core( ...
    -1,...
    options,...
    db,...
    rho,...
    scaled_M,...
    scaled_factors,...
    n_sample,...
    i,...
    y,...
    y_sign);

z(counter)=s_k1(1);
y(i)=s_k1(2);
y(n_sample+1)=s_k1(3);
obj_1=ones(1,n_sample+1)*y + db'*z;
z(counter)=s_k2(1);
y(i)=s_k2(2);
y(n_sample+1)=s_k2(3);
obj_2=ones(1,n_sample+1)*y + db'*z;
obj=[obj_1 obj_2];
min_idx=find(obj==min(obj));
min_idx=min_idx(1);
s_k=[s_k1 s_k2];
s_k=s_k(:,min_idx);
y=s_k(2:3);
z=s_k(1);
end

