function [z]=LP_solve_offdia( ...
    n_sample,...
    scaled_M,...
    scaled_factors,...
    rho,...
    i,...
    db,...
    options,...
    counter,...
    y,...
    z)

[ s_k1 ] = ...
    LP_solve_offdia_core( ...
    1,...
    options,...
    db(counter),...
    rho,...
    scaled_M,...
    scaled_factors,...
    n_sample,...
    i);

[ s_k2 ] = ...
    LP_solve_offdia_core( ...
    -1,...
    options,...
    db(counter),...
    rho,...
    scaled_M,...
    scaled_factors,...
    n_sample,...
    i);

z(counter)=s_k1;
obj_1=ones(1,n_sample+1)*y + db'*z;
z(counter)=s_k2;
obj_2=ones(1,n_sample+1)*y + db'*z;
obj=[obj_1 obj_2];
min_idx=obj==min(obj);
s_k=[s_k1 s_k2];
z=s_k(min_idx);
end

