function [ s_k ] = ...
    LP_solve_offdia_core( ...
    sign_vec,...
    options,...
    db,...
    rho,...
    scaled_M,...
    scaled_factors,...
    n_sample,...
    i)
LP_A=zeros(2,1);
LP_b=zeros(2,1);
LP_A(1)=sign_vec*sign(scaled_factors(i,n_sample+1))*abs(scaled_factors(i,n_sample+1));
LP_A(2)=sign_vec*sign(scaled_factors(n_sample+1,i))*abs(scaled_factors(n_sample+1,i));
remaning_idx=1:n_sample+1;
remaning_idx([i n_sample+1])=[];
LP_b(1)=scaled_M(i,i)-sum(abs(scaled_M(i,remaning_idx)))-rho;
remaning_idx=1:n_sample;
remaning_idx(i)=[];
LP_b(2)=scaled_M(n_sample+1,n_sample+1)-sum(abs(scaled_M(n_sample+1,remaning_idx)))-rho;
try
    s_k = linprog(db,...
        LP_A,LP_b,...
        [],[],...
        [],[],options);
    if isempty(s_k)
        s_k=Inf;
    end
catch
    s_k=Inf;
end
end

