function [ M_current_eigenvector0,...
    scaled_M,...
    scaled_factors ] = ...
    compute_scalars( ...
    M_updated_current,...
    M_current_eigenvector0 )

[M_current_eigenvector0,~] = ...
    lobpcg_fv(...
    M_current_eigenvector0,...
    M_updated_current,...
    1e-4,...
    200);

a=M_current_eigenvector0(:,1);

scaled_M = (1./a) .* M_updated_current .* a';
scaled_factors = (1./a) .* ones(length(M_current_eigenvector0)) .* a';

end

